// GENERATED FILE - do not edit by hand.
// Regenerate with: python scratch/gen_pixellab_assets.py
//
// PixelLab pixel-art silhouette layer (Mimic Pixel Art Implementation Plan,
// section 4): maps display words from all three language packs (EN, FIL, CEB)
// to canonical concept slugs, falls back to archetype keywords for custom
// Forge words, and filters every tier by the sprites that actually ship in
// assets/images/silhouettes/ so a partially generated library degrades to the
// vector painter instead of a missing-asset box.

/// Resolves a display word to an available `sil_<slug>.png` pixel sprite.
class PixelSilhouetteResolver {
  PixelSilhouetteResolver._();

  /// Asset folder shared by every silhouette sprite (plan section 4).
  static const String assetPrefix = 'assets/images/silhouettes/sil_';
  static const String assetSuffix = '.png';

  /// 237 unique base-pack concepts across 6 packs (see
  /// scratch/pixellab_batch_prompts.json for the full prompt manifest).

  /// Slugs with a PNG on disk. Checked on every resolution tier.
  static const Set<String> _availableSprites = {
    'abattoir',
    'alibi',
    'altar',
    'amulet',
    'asylum',
    'attic',
    'axe',
    'bad_luck',
    'bakunawa',
    'banshee',
    'basement',
    'breeze',
    'cabin',
    'card',
    'castle',
    'catacombs',
    'cauldron',
    'cave',
    'cemetery',
    'centaur',
    'ceremony',
    'chainsaw',
    'chalice',
    'chupacabra',
    'cleansing',
    'club',
    'coffin',
    'coldroom',
    'colossus',
    'cottage',
    'coven',
    'crypt',
    'cup',
    'curse',
    'daemon',
    'dagger',
    'diary',
    'donation',
    'dungeon',
    'evidence',
    'excuse',
    'exorcism',
    'forest',
    'garden',
    'ghost',
    'ghost_town',
    'gnome',
    'goblin',
    'graveyard',
    'grimoire',
    'harpy',
    'history',
    'hospital',
    'illusion',
    'jewelry',
    'kapre',
    'keychain',
    'kitchen',
    'lake',
    'library',
    'lighthouse',
    'magician',
    'mambabarang',
    'manananggal',
    'mausoleum',
    'maze',
    'meeting',
    'mine',
    'morgue',
    'necromancy',
    'nuno',
    'park',
    'pentagram',
    'phantom_fire',
    'pipeline',
    'poltergeist',
    'pot',
    'prison',
    'ritual',
    'ruins',
    'sacrificing',
    'safe',
    'santelmo',
    'scalpel',
    'scythe',
    'sea_serpent',
    'seance',
    'sewer',
    'shadow',
    'sickle',
    'sigbin',
    'skull',
    'spell',
    'star',
    'storeroom',
    'swamp',
    'table',
    'talisman',
    'tarot',
    'tikbalang',
    'tiyanak',
    'tunnel',
    'vault',
    'village',
    'warlock',
    'watchtower',
    'white_lady',
    'wish',
    'woods',
  };

  /// Exact base-pack concept words (lowercased EN) -> concept slug.
  static const Map<String, String> _conceptSlugs = {
    'abattoir': 'abattoir',
    'abyss': 'abyss',
    'accident': 'accident',
    'alibi': 'alibi',
    'altar': 'altar',
    'amomongo': 'amomongo',
    'amulet': 'amulet',
    'animal': 'animal',
    'anxiety': 'anxiety',
    'aswang': 'aswang',
    'asylum': 'asylum',
    'attic': 'attic',
    'autopsy': 'autopsy',
    'avalon': 'avalon',
    'bad luck': 'bad_luck',
    'bakunawa': 'bakunawa',
    'bal-bal': 'bal_bal',
    'bandage': 'bandage',
    'banshee': 'banshee',
    'barricade': 'barricade',
    'basement': 'basement',
    'batibat': 'batibat',
    'bedroom': 'bedroom',
    'berberoka': 'berberoka',
    'biringan': 'biringan',
    'blackmail': 'blackmail',
    'blood': 'blood',
    'breeze': 'breeze',
    'bungisngis': 'bungisngis',
    'bunker': 'bunker',
    'bystander': 'bystander',
    'cabin': 'cabin',
    'candle': 'candle',
    'card': 'card',
    'castle': 'castle',
    'catacombs': 'catacombs',
    'cauldron': 'cauldron',
    'cave': 'cave',
    'cemetery': 'cemetery',
    'centaur': 'centaur',
    'ceremony': 'ceremony',
    'chainsaw': 'chainsaw',
    'chalice': 'chalice',
    'checkup': 'checkup',
    'chupacabra': 'chupacabra',
    'cleansing': 'cleansing',
    'cloud': 'cloud',
    'club': 'club',
    'clue': 'clue',
    'cold spot': 'cold_spot',
    'coldroom': 'coldroom',
    'colossus': 'colossus',
    'corpse': 'corpse',
    'cottage': 'cottage',
    'coven': 'coven',
    'crime scene': 'crime_scene',
    'crypt': 'crypt',
    'cup': 'cup',
    'curse': 'curse',
    'cutter': 'cutter',
    'cyanide': 'cyanide',
    'cyclops': 'cyclops',
    'daemon': 'daemon',
    'darkness': 'darkness',
    'decay': 'decay',
    'detective': 'detective',
    'diary': 'diary',
    'dimness': 'dimness',
    'dirt': 'dirt',
    'disease': 'disease',
    'donation': 'donation',
    'door': 'door',
    'doppelganger': 'doppelganger',
    'draft': 'draft',
    'dream': 'dream',
    'dullahan': 'dullahan',
    'dummy': 'dummy',
    'dungeon': 'dungeon',
    'duwende': 'duwende',
    'engine': 'engine',
    'error': 'error',
    'evidence': 'evidence',
    'excuse': 'excuse',
    'exorcism': 'exorcism',
    'fan': 'fan',
    'fear': 'fear',
    'fingerprint': 'fingerprint',
    'flare': 'flare',
    'flashlight': 'flashlight',
    'fog': 'fog',
    'food': 'food',
    'footprint': 'footprint',
    'forest': 'forest',
    'garden': 'garden',
    'generator': 'generator',
    'ghost': 'ghost',
    'ghost town': 'ghost_town',
    'ghoul': 'ghoul',
    'glitch': 'glitch',
    'gnome': 'gnome',
    'goblin': 'goblin',
    'graveyard': 'graveyard',
    'grimoire': 'grimoire',
    'guest': 'guest',
    'hallucination': 'hallucination',
    'harpy': 'harpy',
    'history': 'history',
    'hobby': 'hobby',
    'hole': 'hole',
    'hospital': 'hospital',
    'illusion': 'illusion',
    'infection': 'infection',
    'insomnia': 'insomnia',
    'intruder': 'intruder',
    'isolation': 'isolation',
    'jewelry': 'jewelry',
    'kapre': 'kapre',
    'kelpie': 'kelpie',
    'key': 'key',
    'keychain': 'keychain',
    'kidnapping': 'kidnapping',
    'kitchen': 'kitchen',
    'lake': 'lake',
    'letter': 'letter',
    'leviathan': 'sea_serpent',
    'library': 'library',
    'lighthouse': 'lighthouse',
    'lock': 'lock',
    'loneliness': 'loneliness',
    'magician': 'magician',
    'mambabarang': 'mambabarang',
    'manananggal': 'manananggal',
    'mausoleum': 'mausoleum',
    'maze': 'maze',
    'medicine': 'medicine',
    'meeting': 'meeting',
    'mermaid': 'mermaid',
    'mine': 'mine',
    'mirage': 'mirage',
    'mirror': 'mirror',
    'monster': 'monster',
    'morgue': 'morgue',
    'motive': 'motive',
    'murder': 'murder',
    'murmurs': 'murmurs',
    'mutation': 'mutation',
    'necromancy': 'necromancy',
    'nightmare': 'nightmare',
    'nuno sa punso': 'nuno',
    'obsession': 'obsession',
    'obstacle': 'obstacle',
    'officer': 'officer',
    'paint': 'paint',
    'panic': 'panic',
    'paranoia': 'paranoia',
    'park': 'park',
    'patient': 'patient',
    'payment': 'payment',
    'pentagram': 'pentagram',
    'phantom fire': 'phantom_fire',
    'phobia': 'phobia',
    'phone': 'phone',
    'pipeline': 'pipeline',
    'pistol': 'pistol',
    'poison': 'poison',
    'poltergeist': 'poltergeist',
    'pot': 'pot',
    'premonition': 'premonition',
    'prison': 'prison',
    'pugot': 'pugot',
    'radio': 'radio',
    'ransom': 'ransom',
    'rations': 'rations',
    'reason': 'reason',
    'reflection': 'reflection',
    'ritual': 'ritual',
    'room': 'room',
    'ruins': 'ruins',
    'rust': 'rust',
    'sacrificing': 'sacrificing',
    'safe': 'safe',
    'safe room': 'safe_room',
    'santelmo': 'santelmo',
    'scar': 'scar',
    'scare': 'scare',
    'serum': 'serum',
    'sewer': 'sewer',
    'shadow': 'shadow',
    'shelter': 'shelter',
    'shotgun': 'shotgun',
    'sick person': 'sick_person',
    'sigbin': 'sigbin',
    'silhouette': 'silhouette',
    'sirena': 'sirena',
    'smudge': 'smudge',
    'spell': 'spell',
    'sprite': 'sprite',
    'stalker': 'stalker',
    'star': 'star',
    'static': 'static',
    'storeroom': 'storeroom',
    'stranger': 'stranger',
    'succubus': 'succubus',
    'sugar': 'sugar',
    'suspect': 'suspect',
    'swamp': 'swamp',
    'séance': 'seance',
    'table': 'table',
    'talisman': 'talisman',
    'tape': 'tape',
    'tarot': 'tarot',
    'thought': 'thought',
    'tikbalang': 'tikbalang',
    'tiredness': 'tiredness',
    'tiyanak': 'tiyanak',
    'tool': 'tool',
    'torch': 'torch',
    'trap': 'trap',
    'tunnel': 'tunnel',
    'twin': 'twin',
    'vaccine': 'vaccine',
    'vault': 'vault',
    'victim': 'victim',
    'village': 'village',
    'visit': 'visit',
    'warlock': 'warlock',
    'watchtower': 'watchtower',
    'weapon': 'weapon',
    'werewolf': 'werewolf',
    'whispers': 'whispers',
    'white lady': 'white_lady',
    'white noise': 'white_noise',
    'wish': 'wish',
    'witness': 'witness',
    'woods': 'woods',
    'yeti': 'yeti',
    'zombie': 'zombie',
  };

  /// FIL / CEB pack words (lowercased) -> the same concept slug. Pairs are
  /// index-aligned with the EN packs (WordPackData.getPacksForLanguage), so
  /// localized words inherit their concept's sprite automatically.
  static const Map<String, String> _localizedSlugs = {
    'agimat': 'talisman',
    'aklat-mahika': 'grimoire',
    'aklatan': 'library',
    'aksidente': 'accident',
    'alahas': 'jewelry',
    'anino': 'shadow',
    'anting-anting': 'amulet',
    'asukal': 'sugar',
    'asukar': 'sugar',
    'autopsiya': 'autopsy',
    'babaeng nakaputi': 'white_lady',
    'babag': 'obstacle',
    'babaye nga puti': 'white_lady',
    'bagulbol': 'murmurs',
    'bakas ng daliri': 'fingerprint',
    'bakas ng paa': 'footprint',
    'bakuna': 'vaccine',
    'balbal': 'bal_bal',
    'bangin': 'abyss',
    'bangkay': 'corpse',
    'bangungot': 'nightmare',
    'bangungot-demonyo': 'succubus',
    'bantayan': 'watchtower',
    'baraha': 'card',
    'barang': 'spell',
    'barikada': 'barricade',
    'baryo': 'village',
    'bayad': 'payment',
    'bayan ng multo': 'ghost_town',
    'benda': 'bandage',
    'biktima': 'victim',
    'bilanggoan': 'prison',
    'bilangguan': 'prison',
    'bisita': 'guest',
    'bitag': 'trap',
    'bituin': 'star',
    'bituon': 'star',
    'bobeda': 'vault',
    'bodega': 'storeroom',
    'bugnaw nga dapit': 'cold_spot',
    'bulong': 'whispers',
    'bung-aw': 'abyss',
    'butas': 'hole',
    'dahilan': 'excuse',
    'damgo': 'dream',
    'damgo-mananap': 'succubus',
    'dapit sa krimen': 'crime_scene',
    'demonyo': 'daemon',
    'detektib': 'detective',
    'dilim': 'darkness',
    'donasyon': 'donation',
    'dugo': 'blood',
    'dumi': 'dirt',
    'duwendeng pula': 'goblin',
    'ebidensya': 'evidence',
    'eksorsismo': 'exorcism',
    'engkanto': 'sprite',
    'engkanto ng lupa': 'gnome',
    'eskopeta': 'shotgun',
    'estranghero': 'stranger',
    'freezer': 'coldroom',
    'gabon': 'fog',
    'galamiton': 'tool',
    'gamayng diwata': 'sprite',
    'gamayng halimaw': 'goblin',
    'gamot': 'medicine',
    'gubat': 'forest',
    'guho': 'ruins',
    'halad': 'sacrificing',
    'halimaw': 'monster',
    'halimaw ng dagat': 'sea_serpent',
    'halusinasyon': 'hallucination',
    'hamog': 'fog',
    'hanap': 'dimness',
    'hardin': 'garden',
    'hayop': 'animal',
    'higanteng bato': 'colossus',
    'higanteng bitin': 'sea_serpent',
    'higanteng isa-mata': 'cyclops',
    'higanteng matsing': 'yeti',
    'hiling': 'wish',
    'hilo': 'poison',
    'hinagiban': 'weapon',
    'hinungdan': 'reason',
    'hugaw': 'dirt',
    'hunahuna': 'thought',
    'hunghong': 'whispers',
    'huyohoy': 'breeze',
    'ibon-halimaw': 'harpy',
    'ibon-mananap': 'harpy',
    'ilusyon': 'illusion',
    'imburnal': 'sewer',
    'impeksyon': 'infection',
    'ingay': 'white_noise',
    'isip': 'thought',
    'kabalaka': 'anxiety',
    'kabalyerong pugot': 'dullahan',
    'kabayo ng lawa': 'kelpie',
    'kabayo sa tubig': 'kelpie',
    'kabayo-tao': 'centaur',
    'kabayo-tawo': 'centaur',
    'kabin': 'cabin',
    'kagun-oban': 'ruins',
    'kaha': 'safe',
    'kahadlok': 'scare',
    'kain-bangkay': 'ghoul',
    'kakahoyan': 'woods',
    'kakahuyan': 'woods',
    'kakapoy': 'tiredness',
    'kalawang': 'rust',
    'kalayo sa kalag': 'phantom_fire',
    'kaldero': 'cauldron',
    'kalingawan': 'hobby',
    'kalis': 'chalice',
    'kalisang': 'panic',
    'kaluha': 'twin',
    'kalungkutan': 'loneliness',
    'kambal': 'twin',
    'kamingaw': 'loneliness',
    'kandado': 'lock',
    'kandila': 'candle',
    'kangitngit': 'darkness',
    'kasangkapan': 'tool',
    'kasaysayan': 'history',
    'kastilyo': 'castle',
    'katakumba': 'catacombs',
    'kataw': 'mermaid',
    'katayan': 'abattoir',
    'katayanan': 'abattoir',
    'klub': 'club',
    'kubo': 'cottage',
    'kulam': 'spell',
    'kulamnon': 'warlock',
    'kulon': 'pot',
    'kulto': 'coven',
    'kusina': 'kitchen',
    'kutob': 'premonition',
    'kuweba': 'cave',
    'kwarto': 'room',
    'labirinto': 'maze',
    'lagusan': 'tunnel',
    'lamakan': 'swamp',
    'lamesa': 'table',
    'lamlam': 'dimness',
    'lanaw': 'lake',
    'landong': 'shadow',
    'langub': 'cave',
    'lasang': 'forest',
    'lason': 'poison',
    'latian': 'swamp',
    'lawa': 'lake',
    'libangan': 'hobby',
    'libingan': 'graveyard',
    'librarya': 'library',
    'libro sa salamangka': 'grimoire',
    'ligtas na silid': 'safe_room',
    'lit-ag': 'trap',
    'lobo-tao': 'werewolf',
    'lobo-tawo': 'werewolf',
    'lubnganan': 'graveyard',
    'lukat': 'ransom',
    'lungag': 'hole',
    'lungsod sa multo': 'ghost_town',
    'luwas nga kwarto': 'safe_room',
    'makina': 'engine',
    'malamig na lugar': 'cold_spot',
    'malas': 'bad_luck',
    'mali': 'error',
    'malikmata': 'mirage',
    'mamarang': 'warlock',
    'mangkukulam': 'warlock',
    'manika': 'dummy',
    'manloloob': 'intruder',
    'mansa': 'smudge',
    'mantsa': 'smudge',
    'manunulod': 'intruder',
    'manyika': 'dummy',
    'marka sa tudlo': 'fingerprint',
    'masakiton': 'sick_person',
    'mawsoleo': 'mausoleum',
    'may sakit': 'sick_person',
    'mental': 'asylum',
    'mesa': 'table',
    'minahan': 'mine',
    'minatay': 'corpse',
    'morge': 'morgue',
    'motibo': 'motive',
    'multo': 'ghost',
    'multong apoy': 'phantom_fire',
    'mutasyon': 'mutation',
    'nawala nga syudad': 'avalon',
    'nawawalang bayan': 'avalon',
    'nekromansya': 'necromancy',
    'nitso': 'crypt',
    'obsesyon': 'obsession',
    'ospital': 'hospital',
    'pag-aalay': 'sacrificing',
    'pag-iisa': 'isolation',
    'pag-inusara': 'isolation',
    'pagbisita': 'visit',
    'pagdagit': 'kidnapping',
    'pagdukot': 'kidnapping',
    'paghinlo': 'cleansing',
    'pagkabalisa': 'anxiety',
    'pagkabulok': 'decay',
    'pagkadunot': 'decay',
    'pagkain': 'food',
    'pagkaon': 'food',
    'pagkapagod': 'tiredness',
    'pagkasindak': 'panic',
    'paglilinis': 'cleansing',
    'pagpaslang': 'murder',
    'pagpatay': 'murder',
    'pagpupulong': 'meeting',
    'palatandaan': 'clue',
    'palayok': 'pot',
    'pamutol': 'cutter',
    'panaginip': 'dream',
    'pangandoy': 'wish',
    'panganod': 'cloud',
    'pangilkil': 'blackmail',
    'pangingikil': 'blackmail',
    'pantubos': 'ransom',
    'paranoya': 'paranoia',
    'parke': 'park',
    'parola': 'lighthouse',
    'pasangil': 'excuse',
    'pasyente': 'patient',
    'payag': 'cottage',
    'peklat': 'scar',
    'pentagrama': 'pentagram',
    'piitan': 'dungeon',
    'pinangyarihan': 'crime_scene',
    'pinto': 'door',
    'pintura': 'paint',
    'pistola': 'pistol',
    'pobya': 'phobia',
    'pulis': 'officer',
    'pultahan': 'door',
    'radyo': 'radio',
    'rason': 'reason',
    'rasyon': 'rations',
    'repleksyon': 'reflection',
    'ritwal': 'ritual',
    'saba': 'white_noise',
    'sagabal': 'obstacle',
    'sakit': 'disease',
    'saksi': 'witness',
    'salamangkero': 'warlock',
    'salamin': 'mirror',
    'samin': 'mirror',
    'sandata': 'weapon',
    'sayop': 'error',
    'seance': 'seance',
    'sementeryo': 'cemetery',
    'seremonya': 'ceremony',
    'silid': 'room',
    'silong': 'basement',
    'silonganan': 'shelter',
    'silungan': 'shelter',
    'silweta': 'silhouette',
    'simoy': 'breeze',
    'sipsip-dugo': 'chupacabra',
    'sulat': 'letter',
    'sulo': 'torch',
    'sumisipsip ng dugo': 'chupacabra',
    'sumpa': 'curse',
    'susi': 'key',
    'suspetsado': 'suspect',
    'tagahanga': 'fan',
    'tagamasid': 'bystander',
    'takot': 'scare',
    'talaadlawan': 'diary',
    'talaarawan': 'diary',
    'tambal': 'medicine',
    'tanaman': 'garden',
    'taong-dagat': 'mermaid',
    'tasa': 'cup',
    'tawo nga walay ulo': 'dullahan',
    'tawo sa bungtod': 'gnome',
    'taya': 'rust',
    'telepono': 'phone',
    'teyp': 'tape',
    'tigkaon-patay': 'ghoul',
    'tigom': 'meeting',
    'tigtan-aw': 'bystander',
    'timailhan': 'clue',
    'tsekap': 'checkup',
    'tubo': 'pipeline',
    'tulganan': 'bedroom',
    'tunel': 'tunnel',
    'tunglo': 'curse',
    'tunob': 'footprint',
    'ulap': 'cloud',
    'unggoy-halimaw': 'yeti',
    'ungol': 'murmurs',
    'usa-mata': 'cyclops',
    'uwat': 'scar',
    'yawi': 'key',
  };

  /// Archetype keyword fallback for words that are not base-pack concepts
  /// (custom Forge words, future packs). Longest keyword first.
  static const Map<String, String> _keywordSlugs = {
    'ax': 'axe',
    'axe': 'axe',
    'blade': 'dagger',
    'bone': 'skull',
    'casket': 'coffin',
    'cemetery': 'cemetery',
    'chainsaw': 'chainsaw',
    'cleaver': 'dagger',
    'coffin': 'coffin',
    'crowbar': 'axe',
    'crypt': 'coffin',
    'cutlass': 'dagger',
    'dagger': 'dagger',
    'grave': 'cemetery',
    'graveyard': 'cemetery',
    'hammer': 'axe',
    'hatchet': 'axe',
    'headstone': 'cemetery',
    'knife': 'dagger',
    'machete': 'dagger',
    'reaper': 'scythe',
    'sarcophagus': 'coffin',
    'scalpel': 'scalpel',
    'scythe': 'scythe',
    'sickle': 'sickle',
    'skeleton': 'skull',
    'skull': 'skull',
    'sword': 'dagger',
    'tomb': 'coffin',
  };

  /// Slugs that currently ship a sprite asset.
  static Set<String> get availableSprites => _availableSprites;

  /// Full asset path for a sprite slug, e.g. `sil_tikbalang.png` ->
  /// `assets/images/silhouettes/sil_tikbalang.png`.
  static String assetPath(String slug) => '$assetPrefix$slug$assetSuffix';

  /// Concept slug for [word] in any supported language, ignoring whether the
  /// sprite exists yet (tooling / tests).
  static String? conceptSlug(String word) {
    final key = word.toLowerCase().trim();
    return _conceptSlugs[key] ?? _localizedSlugs[key];
  }

  /// Available pixel sprite slug for [word], or null when the word should
  /// render through the zero-fail vector CustomPainter fallback.
  static String? resolve(String word) {
    final key = word.toLowerCase().trim();
    final concept = _conceptSlugs[key] ?? _localizedSlugs[key];
    if (concept != null && _availableSprites.contains(concept)) {
      return concept;
    }
    for (final entry in _keywordSlugs.entries) {
      if (_availableSprites.contains(entry.value) && _containsWord(key, entry.key)) {
        return entry.value;
      }
    }
    return null;
  }

  /// Word-boundary match so 'taxed' never triggers the 'axe' keyword while
  /// 'Rusty Dagger' does.
  static bool _containsWord(String text, String keyword) {
    var index = text.indexOf(keyword);
    while (index != -1) {
      final startsBoundary = index == 0 || text[index - 1] == ' ';
      final end = index + keyword.length;
      final endsBoundary = end == text.length || text[end] == ' ';
      if (startsBoundary && endsBoundary) return true;
      index = text.indexOf(keyword, index + 1);
    }
    return false;
  }
}
